import { useEffect, useState} from "react";
import { useParams } from "react-router-dom";
import salesOrderApi from "../../api/salesOrderApi";
import { formatCurrency } from "../../utils/currency";  
import CompanyPrintHeader from "../../components/print/CompanyPrintHeader"; 

export default function SalesOrderPrint() {
  const { id } = useParams();

  const [so, setSo] = useState(null);

 

  useEffect(() => {
    const load = async () => {
      const data = await salesOrderApi.getById(id);
      setSo(data);
    };

    load();
  }, [id]);

 
useEffect(() => {
  const handleAfterPrint = () => {
    window.close();
  };

  window.addEventListener("afterprint", handleAfterPrint);

  return () => {
    window.removeEventListener(
      "afterprint",
      handleAfterPrint
    );
  };
}, []);

useEffect(() => {
  if (!so) return;

  const timer = setTimeout(() => {
    window.print();
  }, 500);

  return () => clearTimeout(timer);
}, [so]);

  if (!so) {
    return <div>Loading...</div>;
  }

  return (
    <div
      id="print-area"
      className="max-w-4xl mx-auto bg-white p-8"
    >
      {/* Company Header */}

      <CompanyPrintHeader
        documentTitle="SALES ORDER"
        documentNumber={so.so_number}
      />

      {/* Header Information */}

      <div className="mb-6">

        <p>
          <strong>SO Number:</strong>{" "}
          {so.so_number}
        </p>

        <p>
          <strong>Customer:</strong>{" "}
          {so.customer_name}
        </p>

        <p>
          <strong>Payment Type:</strong>
          {so.payment_method || "-"}  
        </p>

        <p>
          <strong>Credit Terms:</strong>
          {so.credit_days || "-"} Days
        </p>

        <p>
          <strong>Due Date:</strong>
          {so.due_date || "-"}
        </p>

        <p>
          <strong>Status:</strong>{" "}
          {so.status}
        </p>

        <p>
          <strong>Date:</strong>{" "}
          {new Date(
            so.created_at
          ).toLocaleDateString()}
        </p>

      </div>

      {/* Confirmation */}

      <div className="mb-6">

        <p>
          <strong>Confirmed By:</strong>{" "}
          {so.confirmed_by_name || "-"}
        </p>

        <p>
          <strong>Confirmed At:</strong>{" "}
          {so.confirmed_at
            ? new Date(
                so.confirmed_at
              ).toLocaleString()
            : "-"}
        </p>

      </div>

      {/* Items */}

      <table className="w-full border border-collapse">

        <thead>

          <tr className="bg-gray-100">

            <th className="border p-2 text-left">
              Item
            </th>

            <th className="border p-2">
              Qty
            </th>

            <th className="border p-2">
              Unit Price
            </th>

            <th className="border p-2">
              Total
            </th>

          </tr>

        </thead>

        <tbody>

          {so.items.map(item => (
            <tr key={item.inventory_id}>

              <td className="border p-2">
                {item.item_name}
              </td>

              <td className="border p-2 text-center">
                {item.quantity}
              </td>

              <td className="border p-2 text-right">
                {formatCurrency(item.unit_price)}
              </td>

              <td className="border p-2 text-right">
                {formatCurrency(item.total_amount)}
              </td>

            </tr>
          ))}

        </tbody>

      </table>

      {/* Total */}

      <div className="mt-6 text-right">

        <h2 className="text-xl font-bold">
          Total: 
          {formatCurrency(so.total_amount)}
        </h2>

      </div>

      {/* Signatures */}

      <div className="mt-10 border-t pt-4 text-sm">

        <div className="flex justify-between">

          <div>
            ______________________
            <br />
            Prepared By
          </div>

          <div>
            ______________________
            <br />
            Approved By
          </div>

        </div>

        <div className="mt-6 text-center text-gray-500">

          Generated by Ashengo Inventory Management System

        </div>

      </div>

    </div>
  );
}